# Generated by Django 3.2.5 on 2021-07-16 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_auto_20210716_1632'),

    ]

    operations = [
        migrations.RenameField(
            model_name='country',
            old_name='code',
            new_name='CODE'
        )
    ]
